server:
  port: 9000

spring:
  application:
    name: monitor-server
  cloud:
    config:
      uri: http://localhost:8888  # config-server 地址

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"