server:
  port: 8082

spring:
  application:
    name: order-service
  zipkin:
    base-url: http://localhost:9411  # Zipkin 服务器地址

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
  timelimiter:
    instances:
      user-service:
        timeoutDuration: 2s
management:
  tracing:
    sampling:
      probability: 1.0  # 100% 采样
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId},spanId=%X{spanId}]"